version: "3"

services:

  jupyter:
    restart: always
    image: jupyter:1
    command: bash -c "jupyter notebook --no-browser --ip=0.0.0.0 --allow-root --port 8888"
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - jupyter:/var/lib/jupyter/

volumes:
  jupyter:
